name: CI - Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  test:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./packages/web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18.7.0'
          check-latest: true

      - name: Install Npm Dependencies
        run: yarn install        

      - name: Build App
        run: yarn build

      - name: Run tests with jest
        run: yarn test:ci

      - name: Cypress.io
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./packages/web
          start: yarn start
          wait-on: 'http://localhost:3000'